name: .NET CI

on:
  # Run CI on pushes to main and pull requests into main
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo code
      - uses: actions/checkout@v3

      # 2. Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore JJIMP.sln

      # 4. Build the solution in Release mode
      - name: Build
        run: dotnet build JJIMP.sln --configuration Release --no-restore

      # 5. Run xUnit tests
      - name: Test
        run: dotnet test JJIMP.Tests/JJIMP.Tests.csproj --configuration Release --no-build
